### PR TITLE
Eco-cosmetics

### PR DESCRIPTION
**Pull request by edgarlokys**
https://edgarlokys.github.io/Eco_cosmetics/

### CODE REVIEW

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
2023-03-14_12h02_11
Just switch places for blocks

**Comment by edgarlokys** [comment]
I need the photo to be above the header__content, but when I do that, they don't line up, if I make it below, it won't work for you on small screens, how do I fix it?

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
If you have questions - ask them in fe_chat

**Review by mykhalenych — CHANGES_REQUESTED** [review]
add for 'grid__item-desktop--2-6 grid__item-tablet--1-6'
`grid-row: 1;`

**Pull request closed without merging**
