### PR TITLE
Header was added

### PR DESCRIPTION
**Pull request by kostiantin-hudzenko**
[DEMO LINK](https://kostiantin-hudzenko.github.io/Eco_cosmetics/)

### CODE REVIEW

**Review by mykhalenych — CHANGES_REQUESTED** [review]
design
Screenshot 2023-02-27 at 17 48 00
your deploy
Screenshot 2023-02-27 at 17 48 44

**Review by etojeDenys — CHANGES_REQUESTED** [review]
looks good just fix this overlapping
image

**Comment by kostiantin-hudzenko** [comment]
> виглядає добре, просто виправте це накладання зображення

I can not understand when this overlay occurs? Because everything works well for me.

**Comment by kostiantin-hudzenko** [comment]
I can not understand when this overlay occurs? Because everything works well for me.

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Great job!

it should take first place 
image

should be sticked to right side
image

my own suggestion: you can remove hover effect from images added just to design section(this image will not do something on click and + this effect on every image is annoying a little )
image

**Pull request closed without merging**
